### ISSUE TITLE
Error compiling configure

### ISSUE THREAD

**Issue by specialpointcentral** [tyyteam/la-seL4#1]
https://github.com/tyyteam/la-seL4/blob/b79126e2b1e0a21822079c04b860689416a704c2/gcc.cmake#L56
did not fit the:
https://github.com/tyyteam/la-seL4/blob/b79126e2b1e0a21822079c04b860689416a704c2/configs/Loongarch64_verified.cmake#L13

They need to use the same name.

Because:
https://github.com/tyyteam/la-seL4/blob/b79126e2b1e0a21822079c04b860689416a704c2/gcc.cmake#L18
will set it.

**Comment by GooTal** [comment]
Thanks for your time.
There are too many cmake files and i didn`t figure them all out. My teammate told me that there is no need to change, cause the following files also set loongarch.

![9}$7T5ZA` WVDEJ}H%U$LN9](https://user-images.githubusercontent.com/40800103/182276504-071d3d13-7340-4099-826a-41fe0c473b9b.png)


![UVFZDBO D$N1V%V~ _76_X](https://user-images.githubusercontent.com/40800103/182276518-d9f33409-d3c9-4c8b-b763-1935ac202b42.png)

![D%~(FW IO`832E}J)SBDIVU](https://user-images.githubusercontent.com/40800103/182276521-70f0e8e5-d895-46ef-b14c-d3053f7e43cd.png)
